### ISSUE TITLE
i3 dot files completly gone

### ISSUE THREAD

**Issue by lookto** [shvedes/dotfiles#1]
I realy appriciated your [i3-gaps catppuccin rice](https://www.reddit.com/r/unixporn/comments/z63pvx/i3gaps_fucking_catppuccin_colors/) on r/unixporn.

You link to this repo regarding your dot files. Sadly you seem to have deleted the whole repo and recreated it instead of branching or just overwriting. So it's impossible to get the dotfiles of that post anymore.

Could you please restore them so people that follow your link can follow along and don't get confussed by your bspwm dots.

**Comment by shvedes** [comment]
Impossible. Of all this, only wallpaper and a heavily modified polybar

**Comment by shvedes** [comment]
Impossible. Of all this, only wallpaper and a heavily modified polybar

**Comment by lookto** [comment]
Then please next time don't just delete a repo. Instead use the proper features to archive/store a version. Create a branch with the old version and modify the master branch if that should represent your configs that you are using at the moment.

Otherwise there is no value in using git or GitHub.

**Comment by shvedes** [comment]
i3 here
